name: bloc_presentation_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  bloc_presentation:
    path: ..
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: '>=2.1.0 < 2.2.0'

flutter:
  uses-material-design: true
