name: bloc_presentation_test
description: A testing library for bloc_presentation.
version: 0.0.1
homepage: https://github.com/leancodepl/bloc_presentation/tree/master/packages/bloc_presentation_test

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  bloc_presentation: ^0.2.1+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: '>=2.1.0 <2.2.0'
