name: bloc_presentation_test_example
description: bloc_presentation_test example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  bloc: ^8.0.0
  bloc_presentation:
    path: ../../bloc_presentation
  bloc_presentation_test:
    path: ..
  bloc_test: 9.1.2
  test: ^1.24.3

dev_dependencies:
  leancode_lint: '>=2.1.0 < 2.2.0'
