name: bloc_presentation publish

on:
  push:
    tags: ['bloc_presentation-v*']

jobs:
  publish:
    name: Publish to pub.dev

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    defaults:
      run:
        working-directory: packages/bloc_presentation

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.6

      - name: Publish
        run: dart pub publish -f
